### ISSUE TITLE
Add fix for primary selection behavior

### ISSUE THREAD

**Issue by maccadia** [SebastianSimon/firefox-selection-fix#10]
Hi,

I successfully modified your script to fix [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1653191) : selected text in url bar is not in primary selection when using CTRL+L or clickSelectAll. Personally I use CTRL+L to select the URL in the address bar. This use to put the URL in primary selection so that I can paste it somewhere with middle click. I use this a lot to copy/paste links.

After some trial and error, I found that adding this line in your script works (I'm not sure why or what side effects to expect) : 
```bash
edit_file 'selection' 's#!this.window.windowUtils.isHandlingUserInput ||#//!this.window.windowUtils.isHandlingUserInput ||#' "${unpack_dir}/modules/UrlbarInput.jsm"
```

I will try to send you a pull request.

**Comment by maccadia** [comment]
@SebastianSimon  You can have a look at what I have done [here](https://github.com/MAccadia/firefox-selection-fix/tree/primary_select_fix). After reflection, I won't send a pull request because, as you said in https://github.com/SebastianSimon/firefox-selection-fix/issues/9#issuecomment-832075523, broadening the scope of your script is a significant task.

**Comment by SebastianSimon** [comment]
So, I’m finally back at this script again. I’m currently trying your suggestion and there are a few undesirable things happening and a few things I can’t yet fully understand:

Ideally, copying selection into the clipboard should happen after these additional cases:

* Pressing <kbd>Ctrl</kbd> + <kbd>L</kbd>
* Pressing <kbd>F6</kbd>
* Single-clicking into URL bar which selects all (if this behavior was enabled again, which now, since one of the recent commits, it can be)
* Single-clicking into search bar which selects all

It shouldn’t happen in this case:

* Switching to another tab

For me, your adjustment works well with <kbd>F6</kbd> and with single-click selecting all.

However, <kbd>Ctrl</kbd> + <kbd>L</kbd> only appears to work immediately after switching a tab. Also, given two tabs A and B, when you focus the URL bar of tab A, then focus the URL bar of tab B, then switch back and forth between these tabs using <kbd>Ctrl</kbd> + <kbd>Tab</kbd> and <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Tab</kbd>, the URL bar will actually become selected. This probably shouldn’t trigger clipboard copying.

However, the selection after a tab switch doesn’t seem to always happen. It may depend on certain mouse events happening in between, and <kbd>Ctrl</kbd> + <kbd>L</kbd> behavior may have something to do with it.

In particular, note that in `UrlbarInput.jsm`, `select` and `_on_select` don’t seem to be always called. `select` not being called probably isn’t so bad, as clipboard copying is handled in `_on_select` anyway.

But why and when `_on_select` is not being called still requires some investigation.

Have you run in any other trouble so far with your suggestion?

**Comment by SebastianSimon** [comment]
Let’s revisit this:

1. Have two tabs open, called tab A and tab B
2. Focus the URL bar of both tabs
3. Switch back and forth between both tabs

Based on some trial and error, it actually looks like there is a timing-based `mousemove` handling:

* If the mouse is not moved at all, and you switch tabs using <kbd>Ctrl</kbd> + <kbd>Tab</kbd> and <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Tab</kbd>, then the URL bar of the tab you’re switching to will always be _selected_.
* If you switch tabs by simply clicking them, then the URL bar will always be _deselected_.
* If you switch tabs using <kbd>Ctrl</kbd> + <kbd>Tab</kbd> and <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Tab</kbd> **while moving the mouse over the tab you’re about to switch to**, then the URL bar will always be _deselected_.
* If you **hover over a tab you want to switch to and not move the mouse for around two seconds** and _then_ click on it, then the URL bar will always be _selected_.

Whether the URL bar of a tab you’re switching to will be selected or not, depends on whether the mouse has been actively moved over the tab within the last two seconds.

Crazy implementation…

**Comment by maccadia** [comment]
I had not noticed all this. I use mostly <kbd>Ctrl</kbd> + <kbd>L</kbd>  and sometimes "single click select all" and I haven't seen any issue so far (but I'm not sure it is very solid / future proof).

Did you use the "primary select fix" in combination with "preventClickSelectAll" ?

#### My setup 

- Ubuntu 20.04
- Firefox 89.0.1
-  `fixfx-selection.sh --fix primaryselect` only (with my version)

#### Tests with one tab

For theses tests, I right click on a link and choose open in new window.

- <kbd>Ctrl</kbd> + <kbd>L</kbd> works (no delay)
- Click in urlbar bar to select all works
- <kbd>F6</kbd> does not work straight away (pressing 3 times <kbd>F6</kbd> work)



With multiple tabs, there is indeed some weird things going on (might be a firefox bug).

**Comment by SebastianSimon** [comment]
> Did you use the "primary select fix" in combination with "preventClickSelectAll" ?

I’m currently testing this with `-o preventClickSelectAll=false`. I’ve tested your version, but currently, I’m just trying to figure out what exactly happens in which situation.

Another case: when a tab shows a loaded page, then if you type something into the URL bar, you can press <kbd>Esc</kbd> to restore the original URL of the tab. The URL gets selected. Should the selected URL also be copied to clipboard in this case?

**Comment by maccadia** [comment]
> Another case: when a tab shows a loaded page, then if you type something into the URL bar, you can press Esc to restore the original URL of the tab. The URL gets selected. Should the selected URL also be copied to clipboard in this case?

My opinion is that it should be copied. There are two competing rationale : one is to say that selecting text is not the intention of the user so it shouldn't alter the clipboard state ; the other is to say that "text selected" implies "text copied to primary selection" whatever the context. I am in favor in the second rationale because, as a user, I want things to be easily predictable. If the text is selected and not copied to primary selection, I feel like there is a bug (that's why [the upstream bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1653191) was created).

**Comment by SebastianSimon** [comment]
> "text selected" implies "text copied to primary selection"

But the selection state of the URL bar is remembered across tabs. If you select the URL in tab A, then switch to tab B to highlight something from the page to insert it back into page A, then upon switching to tab A, the URL bar becomes focused again and sometimes selected, overwriting whatever you just copied in page B. You’d have to always remember to defocus the URL bar before switching tabs.

Or should there be a tweak to not even select the URL bar in the first place when switching tabs?

**Comment by maccadia** [comment]
Well... For me it is "selecting text" (the action) that put the text in primary selection. If the selection state is remembered, switching tabs does not / should not cause a selection event.

LibreOffice Writer does remember selection state when switching from one window to another for example, and last selection wins.

**Comment by SebastianSimon** [comment]
I think I’ll make the tab switch behavior another option. I believe I’m close to a solution, though:

1. <kbd>Ctrl</kbd>+<kbd>L</kbd> goes through `openLocation` in `chrome/browser/content/browser/browser.js:2841`,
2. a tab switch goes through `_adjustFocusAfterTabSwitch` in `chrome/browser/content/browser/tabbrowser.js:1385`,
3. most other edge-cases do not matter because `this._getSelectedValueForClipboard()` is the empty string and the `if (!val) { return; }` in `_on_select` is very useful for this.

I think I can simply set a few custom flags on `window.windowUtils` in each of the methods in cases 1 and 2 that will tell me, where the call came from. Since <kbd>Ctrl</kbd>+<kbd>L</kbd> always triggers `select`, but doesn’t always trigger `_on_select`, I can explicitly call `_on_select` if the flag for `openLocation` is set. These flags would then be cleared in `_on_select`.

I’ll try that later today or tomorrow.

**Comment by SebastianSimon** [comment]
Findings so far:

* Adding these properties on `window.windowUtils` doesn’t work at all due to _“`NS_ERROR_XPC_CANT_MODIFY_PROP_ON_WN`: Cannot modify properties of a `WrappedNative`”_.
* Adding the properties directly on `window` doesn’t throw these errors. There doesn’t seem to be any negative impact on this and this actually seems promising!
* `this._suppressPrimaryAdjustment` must not be adjusted (i.e. `this._suppressPrimaryAdjustment = true; this.inputField.select(); this._suppressPrimaryAdjustment = false;` should not happen; instead `this._suppressPrimaryAdjustment` must be `false` before the `this.inputField.select();` call).

**Comment by maccadia** [comment]
All of this is above my head. I'm sorry I can't help.

**Comment by SebastianSimon** [comment]
Don’t worry, I think it’s finished now: commit 361c393.

There are several edge cases and lots of things to test, and I introduced _two_ sub-options: enabling clipboard selection when switching a tab (which may select the URL bar), and enabling clipboard selection when typing a URL which becomes auto-completed (and the rest of the URL selected).

The `sed` edits are not trivial; there was some asynchronicity and general DOM event uncertainty to handle. I will write an in-depth explanation some day in this repo’s wiki.

**Comment by SebastianSimon** [comment]
I probably should mention it here (but it’s also available in the README):

* The new behavior can be enabled with `./fixfx.sh -o autoSelectCopiesToClipboard`.
* If you want URL bar selection, which is caused by switching tabs, to also be copied to clipboard, use `./fixfx.sh -o autoSelectCopiesToClipboard -o tabSwitchCopiesToClipboard`.
* If you want URL bar selection, which is caused by auto-complete while typing a URL, to also be copied to clipboard, use `./fixfx.sh -o autoSelectCopiesToClipboard -o autoCompleteCopiesToClipboard`.
* If you want all of the above, use `./fixfx.sh -o autoSelectCopiesToClipboard -o tabSwitchCopiesToClipboard -o autoCompleteCopiesToClipboard`.

**Comment by maccadia** [comment]
Thanks !

I'm not sure about the terminology "clipboard". I think there is no buffer for the primary selection (if the application is closed, then the primary selection content is lost). With Wayland I don't know how it works.

Users of the script will probably know what to expect though.
