### ISSUE TITLE
Add /usr/lib/firefox-esr as fallback path

### ISSUE THREAD

**Issue by mirabilos** [SebastianSimon/firefox-selection-fix#7]
Please add `/usr/lib/firefox-esr` as another path to be checked; this is the standard location in Debian.

Thanks!

PS: Can this also be used to disable the annoying “the bar gets a bright blue border and extra contrast on focus”?

**Comment by SebastianSimon** [comment]
Does `whereis firefox` not find `firefox-esr` at all? What is the output of that command on your system? If it doesn’t find it, does `whereis firefox-esr` work? I think this might work; then I don’t need to include a fixed fallback path, but instead use `whereis firefox-esr` as a fallback.

Yes, next week I’ll have the time to include this fallback path and I’ll see what I can do with the focus outline. I know that currently, the Firefox devs are working to revamp the URL bar’s appearance — all the changes we’ve seen in the past months including the increased size on focus — and they’re planning to continue changing the appearance, but for the better, e.g. they want to [no longer enlarge the URL bar on focus in the compact UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1630508).

I was thinking about reverting other changes regarding the URL bar in this script, too, but since it’s actively changing with each release (in Nightly — but there are other release tracks with different changes), it may be difficult to keep track of every change in a timely manner.

**Comment by mirabilos** [comment]
Sebastian Simon dixit:

>Does `whereis firefox` not find `firefox-esr` at all? What is the
>output of that command on your system?

Intersting:

$ whereis firefox
firefox: /usr/bin/firefox
$ ll /usr/bin/firefox
-rwxr-xr-x 1 root root 113 Sep 23 05:53 /usr/bin/firefox*
$ cat /usr/bin/firefox
#!/bin/sh

FIREFOX="$(which firefox)"
[ -x "$FIREFOX.real" ] && exec "$FIREFOX.real" "$@"

exec firefox-esr "$@"


This is the standard Debian setup. (Why whereis anyway,
instead of the standard which utility or command -v?)

>If it doesn’t find it, does `whereis firefox-esr` work? I think this

Hmm, I normally start it as “iceweasel”, but that’s a
compatibility link from previous Debian releases I never
got rid of:

lrwxrwxrwx 1 root root 30 Sep 29 10:01 /usr/bin/iceweasel -> ../lib/firefox-esr/firefox-esr*

But, yes, that does:

$ whereis firefox-esr
firefox-esr: /usr/bin/firefox-esr /usr/lib/firefox-esr /etc/firefox-esr /usr/share/firefox-esr /usr/share/man/man1/firefox-esr.1.gz
$ ll /usr/bin/firefox-esr
lrwxrwxrwx 1 root root 30 Sep 23 05:53 /usr/bin/firefox-esr -> ../lib/firefox-esr/firefox-esr*

This, again, is the standard Debian setup.

>I was thinking about reverting other changes regarding the URL bar in
>this script, too, but since it’s actively changing with each release
>(in Nightly — but there are other release tracks with different
>changes), it may be difficult to keep track of every change in a timely
>manner.

Eh, tricky; my condolence.

Most Debian users, and most enterprise users, get only the
ESR versions anyway, so focus on that first will already help.
As for timing, it might be interesting for you to know that Debian
users got upgraded from 68 ESR to 78 ESR around 5ᵗʰ September;
we stick with the old ESR for pretty long while it’s still
supported. (The nōn-ESR version was around before, but that’s
only installed by people wishing to preview and upgrade often,
not in the normal case.)

Thanks,
//mirabilos
-- 
>> Why don't you use JavaScript? I also don't like enabling JavaScript in
> Because I use lynx as browser.
+1
	-- Octavio Alvarez, me and ⡍⠁⠗⠊⠕ (Mario Lang) on debian-devel

**Comment by SebastianSimon** [comment]
Oh, thanks! This is useful information.

> Why `whereis` anyway, instead of the standard `which` utility or `command -v`?

~Because `which` doesn’t work for a manually installed build, e.g. a Nightly that is directly downloaded from the website. `whereis` works with all install options.~

Because `which` doesn’t check all the paths that `whereis` checks. I put my Firefox Nightly in `/usr/share`, so `which` never worked for me

**Comment by SebastianSimon** [comment]
If you type these two commands, does it say that it found an `omni.ja` in the expected `firefox-esr` path?

```sh
$ firefox_dirs=($(whereis -b firefox-esr firefox | cut --delimiter=' ' --fields=2))
$ for firefox_dir in "${firefox_dirs[@]}"; do [[ -f "${firefox_dir}/browser/omni.ja" ]] && echo "omni.ja found in ${firefox_dir}"; done
```

**Comment by mirabilos** [comment]
Sebastian Simon dixit:

>If you type these two commands, does it say that it found an `omni.ja`
>in the expected `firefox-esr` path?

No, it exits with errorlevel 1.

**Comment by SebastianSimon** [comment]
Okay, then I’d expect this variant to work:

```sh
$ firefox_dirs=($(whereis -b firefox-esr firefox | sed -E -e 's/^.*?:\s*//g' | xargs))
$ for firefox_dir in "${firefox_dirs[@]}"; do if [[ -f "${firefox_dir}/browser/omni.ja" ]]; then echo "omni.ja found in ${firefox_dir}"; fi; done
```

This takes all paths where binaries are found of Firefox ESR and Firefox (in that order) and puts all paths in an array, then tests them for the `browser/omni.ja` path. My first variant assumed that the first returned path contains the `browser/omni.ja` path.

Yeah, the exit code of 1 isn’t relevant; the second line was just a quick-and-dirty test to find the correct install paths. This variant includes a proper `if` statement, so that the result of a failed `[[ -f "${firefox_dir}/browser/omni.ja" ]]` doesn’t turn out to be the final result (with `$?` being `1`).

**Comment by mirabilos** [comment]
Sebastian Simon dixit:

>Okay, then I’d expect this variant to work:
>
>```sh
>$ firefox_dirs=($(whereis -b firefox-esr firefox | sed -E -e 's/^.*?:\s*//g' | xargs))
>$ for firefox_dir in "${firefox_dirs[@]}"; do if [[ -f "${firefox_dir}/browser/omni.ja" ]]; then echo "omni.ja found in ${firefox_dir}"; fi; done
>```

It does:

	omni.ja found in /usr/lib/firefox-esr

I wonder how it will handle both firefox (unstable) and firefox-esr
installed…

	omni.ja found in /usr/lib/firefox-esr
	omni.ja found in /usr/lib/firefox

… ah good. So be prepared for multiple results.

>Yeah, the exit code of 1 isn’t relevant; the second line was just a
>quick-and-dirty test to find the correct install paths. This variant
>includes a proper `if` statement, so that the result of a failed `[[ -f
>"${firefox_dir}/browser/omni.ja" ]]` doesn’t turn out to be the final
>result (with `$?` being `1`).

I know (I’m the developer of the mksh shell ☻).

bye,
//mirabilos
-- 
„Cool, /usr/share/doc/mksh/examples/uhr.gz ist ja ein Grund,
mksh auf jedem System zu installieren.“
	-- XTaran auf der OpenRheinRuhr, ganz begeistert
(EN: “[…]uhr.gz is a reason to install mksh on every system.”)

**Comment by SebastianSimon** [comment]
The current plan is to find all `firefox` and `firefox-esr` paths, plus the path provided by `fallback_firefox_dir`, and check if they contain a `browser/omni.ja`. If none are found, error out; if one is found, use it; if more than one is found, let the user `select` a single path to use. Should be sufficient for now.

Test commit 410b0e7 and see if it now finds and fixes your Firefox ESR. I’ll see about the blue focus outline after that.

In the future, multiple paths may be chosen, but it’s a bit tricky to design this well, all the more so as I’m also planning to introduce options like `--path=/usr/share/firefox`, and so on, so that users aren’t forced to run this interactively (i.e. skip or use defaults for `read`s).

(I might be over-engineering this — almost 200 lines to edit 2 lines in an application that the original devs don’t want to fix…)

> I know (I’m the developer of the mksh shell ☻).

Ah, didn’t realize that; it’s always a surprise who the person on the other side of the screen is!

---

Also, just for the record, I made a mistake in my earlier comment where I said _“Because `which` doesn’t work for a manually installed build”_; that isn’t true — it just doesn’t check all the paths that `whereis` checks. I put my Firefox Nightly in `/usr/share`, so `which` never worked for me. :man_shrugging:

**Comment by mirabilos** [comment]
Sebastian Simon dixit:

>The current plan is to find all `firefox` and `firefox-esr` paths, plus
>the path provided by `fallback_firefox_dir`, and check if they contain
>a `browser/omni.ja`. If none are found, error out; if one is found, use
>it; if more than one is found, let the user `select` a single path to
>use. Should be sufficient for now.

Sounds sensible.

>Test commit 410b0e7 and see if it now finds and fixes your Firefox ESR.

Ah, I already hand-patched the script to work for me…

>I’ll see about the blue focus outline after that.

OK.

>(I might be over-engineering this — almost 200 lines to edit 2 lines in
>an application that the original devs don’t want to fix…)

The original devs are… GNOMEs. Their way or the highway. Meh.
Continuously disappointing since Phoenix…

bye,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999

**Comment by SebastianSimon** [comment]
> Ah, I already hand-patched the script to work for me…

Uhhh… I’ll assume it works. :smile:

**Comment by SebastianSimon** [comment]
> PS: Can this also be used to disable the annoying “the bar gets a bright blue border and extra contrast on focus”?

Yes! Since I’m currently in the process of widening the scope of this script and this repo, I can include a customization of the focus outline — although, now I’m not sure what exactly should change. The expanding (scaling) no longer happens and there doesn’t seem to be a config for it anymore, and the dense layout setting in the Customize Firefox page makes the URL bar look decent:

![System (Toffee Dark for Gnome)](https://user-images.githubusercontent.com/37915283/124195504-e844bd00-daca-11eb-9602-a66685f353af.png)  
![Light](https://user-images.githubusercontent.com/37915283/124195499-e7139000-daca-11eb-8d42-25824308058e.png)  
![Dark](https://user-images.githubusercontent.com/37915283/124195502-e844bd00-daca-11eb-81ce-42908d3e6b78.png)  
![Alpenglow](https://user-images.githubusercontent.com/37915283/124195501-e7ac2680-daca-11eb-84c9-f965893c331f.png)

(In order: system-based theme (Toffee Dark for Gnome in my case), Light theme, Dark theme, Alpenglow theme)

The border is still 2px thick; the brightness is theme-based. I don’t know if the border-width can be changed in a custom theme.

**Comment by mirabilos** [comment]
My window manager does not have such a thing as a “system theme” though.
